name: Build content

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: "x64"
          cache: "pip"
      - name: Set up Node/NPM
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "npm"
      - name: Install Python dependencies
        run: python -m pip install yattag
      - name: Install NPM dependencies
        run: npm install --production=true
      - name: Fetch data
        run: npm run fetch-data
      - name: Build site
        run: npm run build
      - name: Upload site content
        uses: actions/upload-artifact@v4
        with:
          name: site-content
          path: output
