name: Lints

on: [push]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: "x64"
          cache: "pip"
      - name: Install Python dependencies
        run: python -m pip install .[dev]
      - name: Ruff
        run: ruff check src/*.py
      - name: Black
        run: black --check src/*.py
      - name: Mypy
        run: mypy --strict src/*.py
  lint-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node/NPM
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "npm"
      - name: Install NPM dependencies
        run: npm install
      - name: ESLint
        run: npx eslint src/*.ts
